remote_theme: https://github.com/JV-conseil/read-the-docs-jekyll-theme

# Aux links for the upper right navigation
aux_links:
  "View PyPi package":
    - "//pypi.org/project/allowed-ghosts/"

google:
  site_verification: ChPjQbKFflPAwOF9uuYRLEodZBgPjW5CISg0gSsViN0

mouseflow:
  project_api_key: 11a6acbb-5bc8-41ac-b415-731ab78f77e0

posthog:
  project_api_key: phc_f6FrCZbt951cotQoYFi5VAS7KYpyCnpgRcbknlMwBDs

umami:
  website_id: 7670b311-8c77-45fb-a36d-6fecf59bbdac

plugins:
  - jemoji
  - jekyll-avatar
  - jekyll-mentions

readme_index:
  with_frontmatter: true
